colorscheme gruber-darker
set-option global toolsclient t
set-option global jumpclient j
set-option global docsclient d
set-option global ui_options terminal_assistant=cat

map -docstring "Jump to next grep match"     global goto n <esc>:grep-next-match<ret>
map -docstring "Jump to previous grep match" global goto p <esc>:grep-previous-match<ret>
map -docstring "Jump to next make error"     global goto ] <esc>:make-next-error<ret>
map -docstring "Jump to previous make error" global goto [ <esc>:make-previous-error<ret>

hook global RegisterModified '"' %{ nop %sh{
  export kak_client_pid="$kak_client_pid"
  printf %s "$kak_main_reg_dquote" | vis-clipboard --copy
}}
hook global WinCreate ^[^*]+$ %{editorconfig-load}
hook global BufSetOption filetype=python %{
    set-option buffer formatcmd 'ruff format -'
    hook buffer -group format BufWritePost .* format
}
