colorscheme gruber-darker
set-option global toolsclient t
set-option global jumpclient j
set-option global docsclient d
set-option global ui_options terminal_assistant=cat

map -docstring "Jump to next grep match"     global goto n <esc>:grep-next-match<ret>
map -docstring "Jump to previous grep match" global goto p <esc>:grep-previous-match<ret>
map -docstring "Jump to next make error"     global goto ] <esc>:make-next-error<ret>
map -docstring "Jump to previous make error" global goto [ <esc>:make-previous-error<ret>

hook global RegisterModified '"' %{ nop %sh{
  export kak_client_pid="$kak_client_pid" 
  printf %s "$kak_main_reg_dquote" | vis-clipboard --copy
}}

# define-command -docstring "Edit file relative to current buf" -params 1 edit-relative %{ edit "%sh{dirname ""${kak_buffile}""}/%arg{@}" }
# alias global er edit-relative 
# complete-command -menu edit-relative shell-script %{
#     orig="$(realpath --relative-to . $(dirname "$kak_buffile"))"
#     q="${1}"
#     if [ "$(basename "$q")" = ".." ]; then
#       d="$(realpath --relative-to . "$q")"
#     elif [ "$(basename "$q")" = "." ]; then
#       d="$(realpath --relative-to . "$q")"
#     elif [ -n "$q" ]; then
#       if [ "$(printf "$q" | tail -c 1)" = / ]; then
#         d="$q"
#       else
#         d="$(dirname "$q")"
#       fi
#     else
#       d="."
#     fi
#     # echo "orig:$orig"
#     # echo "q:$q"
#     # echo "d:$d"
#     fdfind --base-directory "$orig" --full-path --hidden --exact-depth 1 -- . "$d" | fzf --filter "$q" 
# }
