#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg -r &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="mpd xcompmgr dunst pipewire remaps" # remapd, doesn't work that well with usb hubs.

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# pidof -sx "redshift" || redshift -l 52.30487057853634:4.764923605516801 -b 1.0:0.8 &
pidof -sx "redshift" || redshift -l -8.703101934543335:115.17989920854698 -b 1.0:0.8 &
pidof -sx "unclutter" || unclutter -noevents &

gpg-connect-agent updatestartuptty /bye > /dev/null &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
